<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Title>ERP Library SharedKernel</Title>
    <Description>ERP Library for the critical 'DDD' SharedKernel functions. Adds abstractions for Mediator and FluentResults.</Description>
    <Authors>ERP Contributors</Authors>
    <Company>ERP Organization</Company>
    <Copyright>MIT License</Copyright>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup>
    <RepositoryUrl>https://github.com/erporg/erp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>ERP.SharedKernel</PackageId>
    <PackageProjectUrl>https://github.com/erporg/erp</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>erp;library</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>ERP.ReleaseNotes</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0"/>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2"/>
  </ItemGroup>
</Project>
